name: "Parthiban Loganathan"
description: "Parthi is a student at Columbia University and Managing Partner at Dorm Room Fund. He was previously at Google, KPCB Fellows, Coursera and Sailthru."
url: "http://localhost:4000"
permalink: pretty
paginate: 5
paginate_path: "blog/page:num"
