name: "Parthiban Loganathan"
description: "Personal website of Parthiban Loganathan. Parthi is a software developer studying at Columbia University."
url: "http://localhost:4000"
permalink: pretty
paginate: 5
paginate_path: "blog/page:num"
