name: "Parthiban Loganathan"
description: "Welcome to the personal site of Parthiban Loganathan. Parthi is a software developer studying at Columbia University"

url: "http://localhost:4000"

permalink: pretty
